### ISSUE TITLE
Unable to install PyBluez

### ISSUE THREAD

**Issue by adityanithariya** [adityanithariya/Jarvis#1]
Unable to install PyBluez getting error that Microsoft Visual C++ is required

**Comment by adityanithariya** [comment]
Is there any one who can solve?

**Comment by 1nF0rmed** [comment]
The easiest fix would be to install Visual C++.
https://stackoverflow.com/a/59607118

**Comment by adityanithariya** [comment]
> The easiest fix would be to install Visual C++.
> https://stackoverflow.com/a/59607118

Any other solution

**Comment by 1nF0rmed** [comment]
Shift to any Linux Distro (Ubuntu, Linux Mint, Manjaro,etc)

**Comment by adityanithariya** [comment]
> The easiest fix would be to install Visual C++.
> https://stackoverflow.com/a/59607118

Is it free Visual C++

**Comment by adityanithariya** [comment]
Finally, solved by installing python 3.5 and then installing PyBluez
